spring:
  datasource:
    url: jdbc:oracle:@oracle.fiap.com.br:1521:ORCL
    username: rm98837
    password: 280101
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
